[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink-evm/contracts/"
]

[invariant]
runs = 10
depth = 100
fail_on_revert = false
seed = '0x42'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
